# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(030000)
$foreground = rgb(CA8FAD)
$color0 = rgb(030000)
$color1 = rgb(502A29)
$color2 = rgb(4E1D2C)
$color3 = rgb(562F3A)
$color4 = rgb(57191E)
$color5 = rgb(531D45)
$color6 = rgb(582B44)
$color7 = rgb(AE7692)
$color8 = rgb(7D4B66)
$color9 = rgb(502A29)
$color10 = rgb(4E1D2C)
$color11 = rgb(562F3A)
$color12 = rgb(57191E)
$color13 = rgb(531D45)
$color14 = rgb(582B44)
$color15 = rgb(CEB2C0)
