# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252122)
$foreground = rgb(F9EEE1)
$color0 = rgb(4B4748)
$color1 = rgb(231619)
$color2 = rgb(755041)
$color3 = rgb(795445)
$color4 = rgb(448EB9)
$color5 = rgb(9F836C)
$color6 = rgb(B29B80)
$color7 = rgb(EEDECC)
$color8 = rgb(A79B8F)
$color9 = rgb(2F1D21)
$color10 = rgb(9C6A57)
$color11 = rgb(A1705C)
$color12 = rgb(5BBDF6)
$color13 = rgb(D4AF90)
$color14 = rgb(EECEAA)
$color15 = rgb(EEDECC)
