# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(23232A)
$foreground = rgb(E6FCFD)
$color0 = rgb(494951)
$color1 = rgb(141933)
$color2 = rgb(141933)
$color3 = rgb(3B38A5)
$color4 = rgb(A74B8F)
$color5 = rgb(B389BB)
$color6 = rgb(8BB9BB)
$color7 = rgb(D4F2F4)
$color8 = rgb(94A9AA)
$color9 = rgb(1B2144)
$color10 = rgb(1B2144)
$color11 = rgb(4E4ADC)
$color12 = rgb(DF64BF)
$color13 = rgb(EFB6F9)
$color14 = rgb(B9F6F9)
$color15 = rgb(D4F2F4)
